# set here the same port as in .env file
@port=4000

@localhost=http://localhost:{{port}}

# base API url
@baseAPI={{localhost}}

# artist API url
@artistAPI={{baseAPI}}/artist

# set artistId
@artistId=be8d42b3-045b-47f2-8e5e-276e6086e0ba


### Get all
GET {{artistAPI}}


### Create 
POST {{artistAPI}}
content-type: application/json

{
  "name": "artist",
  "grammy": false
}


### Get by id
GET {{artistAPI}}/{{artistId}}


### Update by id 
PUT {{artistAPI}}/{{artistId}}
content-type: application/json

{
  "name": "artist",
  "grammy": true
}


### Delete user by id
DELETE {{artistAPI}}/{{artistId}}


