services:
  node: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - node_postgres_network
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - ./usr/src/app/node_modules
  
  postgres: 
    build: 
      context: .
      dockerfile: ./postgres/Dockerfile
    command: -p ${POSTGRES_PORT}
    restart: always
    networks:
      - node_postgres_network
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - nest-postgres:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_HOST_PORT}:${ADMINER_PORT}
    networks:
      - node_postgres_network
    depends_on:
      - postgres

volumes:
  nest-postgres:

networks:
  node_postgres_network: