services:
  node: 
    build: .
    restart: always
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment: 
      - PORT=${PORT}
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  
  postgres: 
    build: ./postgres/
    restart: always
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data

networks:
  default:
    name: node_postgres_network